name: ledger_usb
description: A Flutter plugin to operate a Ledger Nano device over USB
version: 1.0.0
homepage: https://github.com/RootSoft/ledger-usb
repository: https://github.com/RootSoft/ledger-usb
issue_tracker: https://github.com/RootSoft/ledger-usb/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.blockshake.ledger
        pluginClass: LedgerUsbPlugin

